version: "3"
 services:
    ssr:
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
        - "3000:3000"
      environment:
        - bookname=人道天堂
        - bookSourceUrl=https://m.shouda8.com
    service:
      image: qingmo/lightink-server:latest
      container_name: lightink-server
      environment:
        - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m -Dspring.profiles.active=prod
        - logDir=/app/log
      ports:
        - "9010:8080"
      volumes:
        - /app/log/qingmo:/log    